### ISSUE TITLE
Turn this into a standalone app

### ISSUE THREAD

**Issue by nt1m** [nt1m/media-player#4]
node-webkit sounds good for now, but it doesn't support the latest awesomeness (for of loops, ...) I use.

**Comment by danimesq** [comment]
You can export as native app for HTML5-based platforms and with runtime for others.

# Operating systems

#### HTML5 based
- [ ] Windows Universal Platform
- [ ] Firefox OS
- [ ] Tizen

#### Need of a runtime
- [ ] Windows XP
- [ ] Windows Vista
- [ ] Windows 7
- [ ] Mac OS
- [ ] Ubuntu Linux
- [ ] Android
- [ ] iOS

# Browsers

#### Current/Stable browsers
- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Opera

#### Upcoaming/Beta browsers
- [ ] Vivaldi
- [ ] Microsoft Edge

**Comment by danimesq** [comment]
In need for runtime, you can use Cordova for mobile systems, and for desktop [open a issue](https://github.com/nwjs/nw.js/issues/new) for [node-webkit](https://github.com/nwjs/nw.js) with your suggestion of features that your media player needs.

**Comment by danimesq** [comment]
Sorry, but this commit don't solve this issue.
Its some work to support all these platforms.

**Comment by nt1m** [comment]
@Plasmmer I've opened #89, the rest should be covered by Electron.
